name: CodeOfFlow
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
version: 1.0.0+1

environment:
  sdk: '>=3.0.1 <4.0.0'

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`.
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  rxdart: ^0.27.7
  # The following adds the Cupertino Icons font to your application.
  cupertino_icons: ^1.0.2
  js: ^0.6.7
  equatable: ^2.0.5
  http: ^0.13.4
  amplify_flutter: ^1.1.0
  amplify_auth_cognito: ^1.1.0
  amplify_authenticator: ^1.1.0
  amplify_api: ^1.1.0
  # amplify_datastore: ^1.1.0-supports-only-mobile
  percent_indicator: ^4.0.1
  intl: ^0.18.0
  google_fonts: ^4.0.0
  carousel_slider: ^4.2.1
  fluttertoast: ^8.2.2
  smooth_page_indicator: ^1.1.0
  flash: ^3.0.5+1
  quickalert: ^1.0.1
  video_player: ^2.6.1
  video_player_web: ^2.0.16
  getwidget: ^3.1.1
  pull_to_refresh: ^2.0.0
  # leak_tracker: any
  url_launcher: ^6.1.11

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/image/unit/
    - assets/image/unit/mobile/
    - assets/image/trigger/
    - assets/image/trigger/mobile/
    - assets/image/button/
